{"is_answered": true, "view_count": 31, "tags": ["python", "pandas"], "last_activity_date": 1468489487, "answer_count": 1, "creation_date": 1468485276, "score": 1, "link": "http://stackoverflow.com/questions/38369291/maybe-a-bug-in-dataframe-reindex", "accepted_answer_id": 38370835, "owner": {"user_id": 6588439, "profile_image": "https://www.gravatar.com/avatar/37bc89e7460443c7838e154ffb3bddf6?s=128&d=identicon&r=PG&f=1", "user_type": "registered", "reputation": 37, "link": "http://stackoverflow.com/users/6588439/zhangtong", "accept_rate": 75, "display_name": "zhangtong"}, "title": "Maybe a bug in DataFrame.reindex ?", "question_id": 38369291}