{"is_answered": true, "view_count": 30, "tags": ["python", "pandas", "subset"], "last_activity_date": 1473885172, "answer_count": 3, "creation_date": 1473884126, "score": 2, "link": "http://stackoverflow.com/questions/39498923/unable-to-subset-pandas-dataframe", "accepted_answer_id": 39499047, "owner": {"user_id": 5179643, "profile_image": "https://www.gravatar.com/avatar/c91397c9f6c5e7402ed0cf8057709630?s=128&d=identicon&r=PG&f=1", "user_type": "registered", "reputation": 56, "link": "http://stackoverflow.com/users/5179643/equanimity", "accept_rate": 61, "display_name": "equanimity"}, "title": "Unable to subset Pandas dataframe", "last_edit_date": 1473884300, "question_id": 39498923}