{"owner": {"display_name": "Ertya98", "reputation": 6, "profile_image": "https://www.gravatar.com/avatar/261c0e66995d245949a435795b1e8c99?s=128&d=identicon&r=PG&f=1", "user_id": 7061775, "user_type": "registered", "link": "http://stackoverflow.com/users/7061775/ertya98"}, "link": "http://stackoverflow.com/questions/40207874/calling-a-function-from-inside-a-function", "tags": ["python", "function", "plot", "nested", "nested-function"], "creation_date": 1477257271, "score": 1, "last_edit_date": 1477348811, "is_answered": true, "view_count": 55, "last_activity_date": 1477348811, "question_id": 40207874, "answer_count": 3, "title": "Calling a function from inside a function"}