{"owner": {"display_name": "M.P.", "reputation": 1, "profile_image": "https://www.gravatar.com/avatar/38c58a28d2f7440ec201a7e34c637bc3?s=128&d=identicon&r=PG&f=1", "user_id": 7063001, "user_type": "registered", "link": "http://stackoverflow.com/users/7063001/m-p"}, "link": "http://stackoverflow.com/questions/40212432/python-3-5-2-typeerror-int-object-is-not-callable", "tags": ["python", "excel", "openpyxl"], "creation_date": 1477292490, "score": -7, "closed_date": 1477294035, "last_edit_date": 1477296882, "is_answered": true, "view_count": 36, "last_activity_date": 1477296882, "question_id": 40212432, "closed_reason": "off-topic", "answer_count": 1, "title": "Python 3.5.2 TypeError:&#39; int &#39; object is not callable"}