{"owner": {"display_name": "Julian ", "reputation": 15, "profile_image": "https://i.stack.imgur.com/JJ3TJ.png?s=128&g=1", "user_id": 6410359, "user_type": "registered", "accept_rate": 100, "link": "http://stackoverflow.com/users/6410359/julian"}, "link": "http://stackoverflow.com/questions/40287453/running-flask-socketio-app-on-pythonanywhere-raises-ioerror", "tags": ["python", "flask", "pythonanywhere", "flask-socketio"], "creation_date": 1477578989, "score": 1, "last_edit_date": 1477587041, "is_answered": true, "view_count": 27, "last_activity_date": 1477587114, "question_id": 40287453, "accepted_answer_id": 40287979, "answer_count": 1, "title": "Running Flask-SocketIO app on PythonAnywhere raises IOError"}