{"owner": {"display_name": "Joe Kasedde", "reputation": 29, "profile_image": "https://i.stack.imgur.com/e00G0.jpg?s=128&g=1", "user_id": 2519473, "user_type": "registered", "accept_rate": 67, "link": "http://stackoverflow.com/users/2519473/joe-kasedde"}, "link": "http://stackoverflow.com/questions/40303317/python-error-attributeerror-user-object-has-no-attribute-set-passsword", "tags": ["python", "django"], "creation_date": 1477651013, "score": 0, "closed_date": 1477654974, "is_answered": false, "view_count": 26, "last_activity_date": 1477651013, "question_id": 40303317, "closed_reason": "off-topic", "answer_count": 0, "title": "Python Error AttributeError: &#39;User&#39; object has no attribute &#39;set_passsword&#39;"}