{"last_activity_date": 1477765954, "owner": {"display_name": "Sankalp Raj", "reputation": 4, "profile_image": "https://lh3.googleusercontent.com/-1xM4lpW7iaU/AAAAAAAAAAI/AAAAAAAAAas/It2rP_VlfwA/photo.jpg?sz=128", "user_id": 7071086, "user_type": "registered", "link": "http://stackoverflow.com/users/7071086/sankalp-raj"}, "is_answered": false, "answer_count": 1, "creation_date": 1477763003, "score": -1, "title": "Python says global name not defined", "tags": ["python", "multithreading", "p2p"], "view_count": 11, "question_id": 40321850, "link": "http://stackoverflow.com/questions/40321850/python-says-global-name-not-defined"}