{"owner": {"display_name": "Falkons", "reputation": 3, "profile_image": "https://www.gravatar.com/avatar/2d0180f4bfb94ab0c554ac4da6532f90?s=128&d=identicon&r=PG&f=1", "user_id": 5106132, "user_type": "registered", "link": "http://stackoverflow.com/users/5106132/falkons"}, "link": "http://stackoverflow.com/questions/40331123/exception-in-mainthread-importerror", "tags": ["python", "python-2.7"], "creation_date": 1477844761, "score": 0, "last_edit_date": 1477845523, "is_answered": false, "view_count": 16, "last_activity_date": 1477845523, "question_id": 40331123, "answer_count": 0, "title": "Exception in &quot;MainThread&quot; [...] ImportError"}